### ISSUE TITLE
Manifold colors

### ISSUE THREAD

**Issue by vkrajnak** [champsproject/ldds#20]
Red for unstable, blue for stable. Will require to give draw_lagrangian_descriptor forward and backward LDs separately instead of sum.

**Comment by broncio123** [comment]
Maybe work on redefinition of colourmap parameters to achieve this.

@VikJGG plots do something like that and when overlaid they look great (pics below). However, is this colour scale tweaking manual?

_Just a thought_: One possible approach would be to take the LD values distribution and define `vmin` and `vmax` passed to `plt.contourf` as a function of the mean and std of LD values. I did something like this for the function `draw_lagrangrian_descriptors`, defining a new variable called `colormap_mode` that implements these changes of vmin/vmax if called with value 2.

![image](https://user-images.githubusercontent.com/17453074/87440917-68d48a00-c5ea-11ea-915e-5091ea593c90.png)

![image](https://user-images.githubusercontent.com/17453074/87440854-5a866e00-c5ea-11ea-8e4e-5cd97cc6bb62.png)

**Comment by vkrajnak** [comment]
Maybe it would be enough to redefine the plotting function to accept LD_forward and LD_backward optionally and depending on which ones are provided, it will draw forward, backward or both on top of each other. This should also be relatively straight-forward.

**Comment by broncio123** [comment]
> Maybe it would be enough to redefine the plotting function to accept LD_forward and LD_backward optionally and depending on which ones are provided, it will draw forward, backward or both on top of each other. This should also be relatively straight-forward.

Nice, can you do this @vkrajnak , please? I think this will enhance the graphical output for the EXAMPLES notebook, both for the book and the package.

**Comment by vkrajnak** [comment]
I can put it on the waiting list

**Comment by broncio123** [comment]
NOTE:
Laplacian filter.

**Comment by vkrajnak** [comment]
For filters, you opened issue #11. Let's keep them out of this issue

**Comment by broncio123** [comment]
> Maybe work on redefinition of colourmap parameters to achieve this.
> 
> @VikJGG plots do something like that and when overlaid they look great (pics below). However, is this colour scale tweaking manual?
> 
> _Just a thought_: One possible approach would be to take the LD values distribution and define `vmin` and `vmax` passed to `plt.contourf` as a function of the mean and std of LD values. I did something like this for the function `draw_lagrangrian_descriptors`, defining a new variable called `colormap_mode` that implements these changes of vmin/vmax if called with value 2.
> 
> ![image](https://user-images.githubusercontent.com/17453074/87440917-68d48a00-c5ea-11ea-915e-5091ea593c90.png)
> 
> ![image](https://user-images.githubusercontent.com/17453074/87440854-5a866e00-c5ea-11ea-8e4e-5cd97cc6bb62.png)

__IMPORTANT NOTE__





> For filters, you opened issue #11. Let's keep them out of this issue

Gradient- and Laplacian-based filters should be defined under a common umbrella. 
I will stick to the other open issue though atm.

**Comment by vkrajnak** [comment]
Addressed in pull request #30
