### ISSUE TITLE
(Draft) Enhancements to extension to high-dimensional systems

### ISSUE THREAD

**Issue by broncio123** [champsproject/ldds#22]
* Add magenta contour to boundaries of LD maps - points satisfying energy conservation
* Adjust plot labels automatically according to visualisation slice input `dof_slice`
* Add method in `tools` to visualise energy level curve (H0)
* Add method in `tools` to overlay Poincare maps on top of the extracted manifold-slice intersections
* Add argument to pass colourmap limits to `draw_lagrangian_descriptor` function
* Add method in `tools` to plot LD values along a user-defined path(s), for examples, a straight line.  
* _TBD during meeting_

**Comment by vkrajnak** [comment]
> * Add argument to pass colourmap limits to `draw_lagrangian_descriptor` function

Done via sliders

**Comment by broncio123** [comment]
Most of these suggested enhancements have been addressed or considered unnecessary during LDDS weekly meetings. 

* Add magenta contour to boundaries of LD maps - points satisfying energy conservation (NEEDLESS)
* Adjust plot labels automatically according to visualisation slice input `dof_slice` (DONE)
* Add method in `tools` to visualise energy level curve (H0) (NEEDLESS)
* Add method in `tools` to overlay Poincare maps on top of the extracted manifold-slice intersections (NEEDLESS)
* Add argument to pass colourmap limits to `draw_lagrangian_descriptor` function (DONE #25 )
* Add method in `tools` to plot LD values along a user-defined path(s), for examples, a straight line. (NEEDLESS)
