### ISSUE TITLE
Add extra benchmark examples to test high-dim extension

### ISSUE THREAD

**Issue by broncio123** [champsproject/ldds#23]
* 3DoF (or higher) Hamiltonian autonomous system

All suggestions are welcome.
Add the name of the system, the number of DOF,  and citation where the system has been studied using LDs.

**Comment by broncio123** [comment]
@VikJGG can you help me with this?
I think Steve mentioned a system during the last group meeting.
I was relying on you to remember it :p

**Comment by vkrajnak** [comment]
Addressed in #44 (resolved)
