### ISSUE TITLE
Port code to CHAMPS organization

### ISSUE THREAD

**Issue by broncio123** [champsproject/ldds#34]
Before importing the repo. 

Question: @Shibabrat @VikJGG @vkrajnak 

After importing the repo to the CHAMPS organization, does the name of the repo matters for future deployment of the package via PIP? (I would love to see people doing: `pip install pylds`!)

But, in a PIP search, there already are packages with names such as `pylds`, `pyld`, `ldpy`, for instance. 

So, do we have to go for a new name?

**Comment by Shibabrat** [comment]
Yes, let's avoid confusion with existing names. We can rename the library as `lagdes`, `lagrangiandes`, or other variations. Also, we might need to incorporate codes in C or Julia or Fortran in the future so let's avoid using `py` in the name.

**Comment by broncio123** [comment]
`pip install ldds`!

**Comment by broncio123** [comment]
Done!
@Shibabrat @VikJGG @vkrajnak @stephenwiggins 
closing issue.
