### ISSUE TITLE
Modify generate_grid to output ndarrays

### ISSUE THREAD

**Issue by broncio123** [champsproject/ldds#35]
This change will affect both versions of `compute_lagrangian_descriptor` in `base.py` and `base_discrete.py`.

So, for LD of continuous systems `y0` will have to be flattened under `compute_lagrangian_descriptor` rather than `generate_grid`, since the integrator requires 1D `arrays` as input to compute LD values, unlike for discrete maps.

**Comment by vkrajnak** [comment]
Is this still an issue?

**Comment by vkrajnak** [comment]
`generate_grid` outputs ndarrays now
