### ISSUE TITLE
Total LD output using `max_gradient` implementation 

### ISSUE THREAD

**Issue by broncio123** [champsproject/ldds#62]
Hi @VikJGG  and @vkrajnak 

I ran two simple tests.

**TEST 1**  Before and After `max_gradient` implementation 

![image](https://user-images.githubusercontent.com/17453074/115732178-a76c5180-a37f-11eb-90ac-77c61e7dfcad.png)
![image](https://user-images.githubusercontent.com/17453074/115732255-b8b55e00-a37f-11eb-9d86-3fc2ed18cdd2.png)

**TEST 2** After using `high_constrast_gradient`
Similar output to Laplacian-based filter solution with single threshold, but now the user would have to set up two thresholds?

![image](https://user-images.githubusercontent.com/17453074/115733456-d33c0700-a380-11eb-9d25-8bcf22c4a936.png)

**Comment by vkrajnak** [comment]
What precisely is the bug? Is it the second figure in Test 1 that seems to have fewer contour levels?

**Comment by vkrajnak** [comment]
@broncio123 Is that what you meant by the issue or something else?

**Comment by vkrajnak** [comment]
No response, I assume this is clear then
