### ISSUE TITLE
Unit test issue 

### ISSUE THREAD

**Issue by broncio123** [champsproject/ldds#66]
I can confirm that unit testing is just not running on my machine (first screenshot). 

![image](https://user-images.githubusercontent.com/17453074/126965376-6cf85cff-e99d-41c7-b27f-54d3c2361021.png)

However, the first time I installed `ldds` and ran the unit test it worked. 
That's how I obtained the output on display in the README file (second screenshot)

![image](https://user-images.githubusercontent.com/17453074/126965750-d9cd3c0c-2b45-41e6-bab9-a2c6554e99f0.png)

**Comment by vkrajnak** [comment]
`python -m unittest` only searches the current folder for test files, hence it should be run from within `ldds/tests`. Do tell if it works for you.

**Comment by vkrajnak** [comment]
Works
